language: android
branches:
  only:
  - master-prod
  - beta-prod
  - feature-integrate_ci
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-26
  licenses:
  - android-sdk-license-.+
script:
  - "./gradlew assembleRelease -PpredatorStoreFile=${storeFile} -PpredatorStorePassword=${storePass} -PpredatorKeyAlias=${keyAlias} -PpredatorKeyPassword=${keyPass}"
before_install:
  - openssl aes-256-cbc -K $encrypted_400f62f18203_key -iv $encrypted_400f62f18203_iv -in keystore.jks.enc -out ~\/.local/.keys/Android\ publishing/Predator/keystore.jks -d
env:
  global:
  - secure: vwhhFkkaw6SoVVReCvBNBaFHzNJlgBZkTulNjPLy6rLufd7UwstZuCV17QS7sqsviPwv0mb9KhVbpXIHjDa+d2AGY8uSCXFOO9gFihHkKMPjhrSeRq2VihALGPT4sxykMqjYHt1s7zzvXeJKW+CHlJwJnd6Gz9KKKA7P0s4+6g+gGkaGcPFtIwut5L767RQhF8dsQvmpOapnjl6LcAPaffAJx1rOpIQdSULZ3UGzbdPYfnHVaHFfGRN6Hi4p7LgKfXgXaONoFPCALOCYhra9EmSXK67Bi1m8eD1f4U7d8/RdnSdtnXbWBHNcBMJpJITnjvd8x8D4zBBWqHXNohoW9/GS5CXib+Oj/KFLHFoUMONOJGT93hmRswhWQqRLu2nmVHRR/iBN+p3wd/WKA8FjbyEN1WIgk/hhF5ResbWodjxE5cfpXelrSfKwX40peHJ9dkKPi1Un2oCZ/46Nu0FxADMf5eFNPew8IYbAPEGae9KiWefByj1Q58EAmNDWKe5chAR4d/CYCzrov4y8ehkJT68TqLaMKlaipwQQfuyq4Nw752qKi61/u9KlK0J5Ojfr4dll/5HCix8YVsPYLJq1GcTC8eVkOPHy0/gkIcy0fZi02315BIdiX+LHNH5b6DfxLGmTQJ2UfNpY3AE0Jy6efZrMXGimTeA0Tz3/MsG+1Ks=
  - secure: tRJdbvDPCStXgTZUQ37WRqOFUf3lBZmRX1jXkL9YfLGW1q4AheOC721b0lG4oYadmFxt9pLhU3yYaKMqe6nWTeVTBkt3Qp1bvGAf8c6HG+Zlj2oq5ct8IXAgH4DiGzXIo0loDuC95HnnCM2XTYVOmnMvWIve4xPmUGEV6sGKaQ3cbycalT0HsD2V6hGXBr2MTQMjNu8gO+oS4af++evi568tbdKr15q8kATLZSsG0nap8AnSGL7+x5W2+MsRgffBrWssdMnMfKro7ig0kuma2kZS3MVbUdGfuUM0HWCRvEaSma/OmYcBM0NQj1lCgAVQKuoDqMT9dBuhuu4RPhN/r4buxO7he32byjJT+AMGbRzsUETkWd0QveROHcGj0UkxqQ7p/Ie7k2TTP5aZo2R5SdisHdJiu+ZkfCJtzCVls75XXdUysu1wf/IdDT/MFAI4eTmLKc5fQof3rNxTY/IhH936B9f3bg1Ms4+KHOvvUZsD5fWDw7kOK+NRtF7dAW9qg5VZR3+DQ3xl8WRzznxpBqtMBxLFc5DSDQaiL+WH78fpqery2d+U4/q8Yrm2ZJ5k1KuCIUPNSBDgK6qoV8v+z4A2/oLZ3XNbaKOK7Y1Fu/s7s2q6xUkUoLA3SlPsI5KCRFpORxR3RI2cUde90uFlzkxo0lx63ixg1lkEcesOOcg=
  - secure: f0Sf+LdJ5CJMMY4Cyruv6bzPByi2233VGQTYjk4XZzwaNj9cQ6b8vzQp2ZcML2GtSJkfby9XvTQxMwmSNBbZXYqW7JHDFt7ATflr9+NaLgMdVhWCsL7akHQJBHZP5xvgNA6dBcUL3ZpneHYyYuQkqjO4wD9xUYU/HGqHb4gxC3FWJacdktukkaH+gkL1/ALluHb6gUYjrUsRNaNKXITsuj7D+ZCQyZklY3YviOPxI8BaNTZcGncQq18tWuSUxgdmyDqCZiOTlB5vJEO78GPz3doAz8aHNagrRcIpj1lyadPvvBxAm1a6KiYyjtHB+AR8XsVNVPsPHrU8VlbpiMSWKpHuaFHk/tDp/LH69upzU0+efkZh4atjluAkUPTGgxAzMccB/BuYFuH2BH8O5esD2Ba12JsKnLUeMJAuDAfXas8d1P3lacA+x0z+w1yn2TgHggM/HaZKsAvR+sxUoTcDxbPvcdIH8UthN1l+HHYluRm7gNK6VxkPAmt8FB2VGs2PMYkpE9g6Xi1ezUqgIT26hAUrkU6noeSKdzv5vKA/Lp04pY+7LUzVAN/rNJ2Kx6Yshlhbjw5uXivJHqGKGEzjrUOX618faAXCfIChMONAtSNfcPLN+ee821vdjayggJ+lQJPLQUdUAzlKYdjxiAHQ/S1k9Ua47WiQ32B3yTfpoTo=
  - secure: qMMXeB5DfTsPQ/b2pqOGyq+f0nOmwsB7X/WDyFfgqBql/y8+0UZV7rm8l3lK9QFfRn3cTwjolprZjR9dmvkdHf29GgO3Xcp0JwEgzNzWAJRVMQpKHP1OB437Fx64WOGVFLosBuwFLVzAF5G/aiNpGn05yZKldoFtmGPnJ4t4bplPuSe3YjnVb6vzh5IPRx97BFyjl88ZhYn2VtaCycZXwmOq4+RM0cwxAR3031jjzJjZ+7/ENuiHEZJNovRlb1lTtgWdcaAiB+HzW4WiTkOT0Vbj4g1DpvmIP6q0SMvmqW5oVM2W32+tVbYX3Riq1SV+ys3C3/Ic8RCd3MTDvtAhDLl+v+BOYgitdTgG5YFHGMUiIDYJusLx0IRRSU30T4ebPY0TnqY0SEbc/lHTUgIqPW++jhrmpnN3eVZHWBvzH6fs9v3dtqXr8VDzosvvNIuek0+Bqs0fbwuljBJdm+fgaaN8LMfVaDYgO6K7rPJkyJYjRAM66UKSeFzhuayY8l6afS+zkYXtcMpk9xPI3cZWdeS+fxND7KvoCv+vi63vfRATVkKo7XYGJ2IIu06x3kHDz8FdVuQdZVxbMR9P2Bk2YhhpzcXQ4FdZbuwJ6nn9rouUnln1OuqPjsHCQQf172l1GvPVUV5GW2JmOSQIBFA10qYWR42RaEOlwJX4AM/tnIs=
